In [1]:
import torch
import numpy as np

# Tensorとは？
- 多次元配列を扱うためのデータ構造
- Numpyのndarrayとほぼ同様のAPIを有しており、GPUによる計算もサポートしている
- PyTorchにおいてテンソルはGPU上でも使用できるため、処理速度の向上させることも可能

## Tensorの初期化

In [2]:
# 初期化されていない行列の作成
print(torch.empty(3, 5))

# 乱数によって初期化された行列の作成
print(torch.rand(3, 5))

# 数値を指定した行列の作成
print(torch.tensor([5.5, 3]))

# 数値0で初期化された行列の作成
print(torch.zeros(3, 5))

# long型の数値1で初期化された行列の作成
print(torch.ones(3, 5, dtype = torch.long))

# データタイプの確認
print(f"Datatype of tensor : {torch.ones(3, 5, dtype = torch.long).dtype}")

# deviceを指定することで CPU or GPU 上にTensorを作成する
print(torch.rand(3, 5, device="cpu"))

# GPUが使用可能か確認する
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

# GPUが使用可能であれば、GPU上にtensorを移動させる
tensor = torch.rand(3, 5)
if torch.cuda.is_available():
    tensor = tensor.to(device)

# Tensorがどこに格納されているか確認
print(f"Device tensor is store on : {tensor.device}")

# 0～9までの値で初期化された1次元行列の作成
print(torch.arange(0, 10))

tensor([[ 4.7881e+30,  4.5580e-41, -8.5924e+18,  3.0803e-41,  1.4013e-45],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  6.7262e-44,  0.0000e+00],
        [ 1.1210e-43,  0.0000e+00, -8.5961e+18,  3.0803e-41,  4.7881e+30]])
tensor([[0.8877, 0.9545, 0.1466, 0.1674, 0.4090],
        [0.4844, 0.4971, 0.8304, 0.2081, 0.2087],
        [0.1803, 0.2332, 0.6525, 0.2482, 0.5982]])
tensor([5.5000, 3.0000])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])
Datatype of tensor : torch.int64
tensor([[0.7934, 0.6615, 0.0822, 0.5980, 0.6312],
        [0.4985, 0.8193, 0.5423, 0.2523, 0.3432],
        [0.5645, 0.4741, 0.3284, 0.0483, 0.8647]])
Using cpu device
Device tensor is store on : cpu
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


## ndarrayとTensorの変換
注：変換前の行列の値を変更すると、変更後の行列も値が変化する

In [3]:
tensor = torch.rand(2, 3)
# Tensor -> Numpy ndarray
# 注：GPU上のtensorはCPU上に移動させる必要がある
np_array = np.array(tensor)
np_array = tensor.numpy()
print(f"numpy : \n{np_array}")

# Numpy ndarray -> Tensor
tensor = torch.from_numpy(np_array)
print(f"tensor : \n{tensor}")

numpy : 
[[0.9219655  0.12488121 0.50690705]
 [0.9741791  0.4045003  0.8102489 ]]
tensor : 
tensor([[0.9220, 0.1249, 0.5069],
        [0.9742, 0.4045, 0.8102]])


## Tensorのインデンシング操作

In [4]:
tensor = torch.rand(4, 4)
# インデックスを指定
print(tensor[0, 1])

# 中の値だけの取り出し
print(f"row(%d) col(%d) is value : %f" % (0, 1, tensor[0, 1].item()))

# 行の取り出し
print("First row : ", tensor[0, :])

# 列の取り出し
print("First column : ", tensor[:, 0])
print("Last column  : ", tensor[:, -1])

# スライスでの取り出し
print(tensor[:, :2])
print(tensor[:, [1, 2]])

# マスク配列を使用して特定の値より大きい部分のみを選択
print(tensor[tensor > 0.5])

# インデックス・スライスを使用した一括代入
tensor[0, 1] = 100
tensor[:, -1] = 200
print(tensor)

# 特定条件の要素のみ置換
tensor[tensor > 0.5] = 1
print(tensor)

tensor(0.4623)
row(0) col(1) is value : 0.462330
First row :  tensor([0.3626, 0.4623, 0.2268, 0.3846])
First column :  tensor([0.3626, 0.3774, 0.4656, 0.5247])
Last column  :  tensor([0.3846, 0.7911, 0.5013, 0.7159])
tensor([[0.3626, 0.4623],
        [0.3774, 0.9863],
        [0.4656, 0.8035],
        [0.5247, 0.1890]])
tensor([[0.4623, 0.2268],
        [0.9863, 0.6810],
        [0.8035, 0.7460],
        [0.1890, 0.3204]])
tensor([0.9863, 0.6810, 0.7911, 0.8035, 0.7460, 0.5013, 0.5247, 0.7159])
tensor([[3.6256e-01, 1.0000e+02, 2.2677e-01, 2.0000e+02],
        [3.7736e-01, 9.8631e-01, 6.8098e-01, 2.0000e+02],
        [4.6560e-01, 8.0354e-01, 7.4602e-01, 2.0000e+02],
        [5.2468e-01, 1.8903e-01, 3.2043e-01, 2.0000e+02]])
tensor([[0.3626, 1.0000, 0.2268, 1.0000],
        [0.3774, 1.0000, 1.0000, 1.0000],
        [0.4656, 1.0000, 1.0000, 1.0000],
        [1.0000, 0.1890, 0.3204, 1.0000]])


## Tensorのサイズ操作

In [5]:
tensor = torch.rand(2, 8)
# Tensorサイズ≒Tensorの形
print(tensor.size())
# リサイズ
print(tensor)
tensor1 = tensor.view(1, 16)
print(tensor1)
tensor2 = tensor.view(-1, 4) # -1を指定するとほかに指定した次元の値から自動で計算
print(tensor2)

# 転置
print(tensor.t())

# 結合
print(torch.cat([tensor, tensor], dim = 0))

torch.Size([2, 8])
tensor([[0.0812, 0.8208, 0.3800, 0.0849, 0.1101, 0.4861, 0.8190, 0.6336],
        [0.4037, 0.9772, 0.4007, 0.9345, 0.7949, 0.2657, 0.9310, 0.8817]])
tensor([[0.0812, 0.8208, 0.3800, 0.0849, 0.1101, 0.4861, 0.8190, 0.6336, 0.4037,
         0.9772, 0.4007, 0.9345, 0.7949, 0.2657, 0.9310, 0.8817]])
tensor([[0.0812, 0.8208, 0.3800, 0.0849],
        [0.1101, 0.4861, 0.8190, 0.6336],
        [0.4037, 0.9772, 0.4007, 0.9345],
        [0.7949, 0.2657, 0.9310, 0.8817]])
tensor([[0.0812, 0.4037],
        [0.8208, 0.9772],
        [0.3800, 0.4007],
        [0.0849, 0.9345],
        [0.1101, 0.7949],
        [0.4861, 0.2657],
        [0.8190, 0.9310],
        [0.6336, 0.8817]])
tensor([[0.0812, 0.8208, 0.3800, 0.0849, 0.1101, 0.4861, 0.8190, 0.6336],
        [0.4037, 0.9772, 0.4007, 0.9345, 0.7949, 0.2657, 0.9310, 0.8817],
        [0.0812, 0.8208, 0.3800, 0.0849, 0.1101, 0.4861, 0.8190, 0.6336],
        [0.4037, 0.9772, 0.4007, 0.9345, 0.7949, 0.2657, 0.9310, 0.8817]])


## Tensorの演算
|演算子|説明|
|:-----|:---|
|dot|ベクトルの内積|
|mv|行列とベクトルの積|
|mm|行列と行列の積|
|matmul|引数の種類によって自動的にdot, mv, mmを選択して実行|
|gesv|LU分解による連立方程式の解|
|eig, symeig|固有値分解（symeigは対称行列用のより効率の良いアルゴリズム）|
|svd|特異値分解|

### ベクトルの演算

In [6]:
v1 = torch.rand([1, 3])
v2 = torch.rand([1, 3])
result = torch.zeros([1, 3])

# ベクトルとスカラーの足し算
print(v1 + 5)
print(torch.add(v1, 5))
print(torch.add(v1, 5, out = result)) # 出力先を引数で指定
print(v1.add_(5)) # Tensorそのものの変更（ip-place：インプレース処理）

# ベクトルの累乗
print(v1 ** 2)

# ベクトル同士の演算
print(v1 + v2)

# 複数の組み合わせ
print(v1 * 10 - v2 / 2 + 6)

tensor([[5.9163, 5.6644, 5.6165]])
tensor([[5.9163, 5.6644, 5.6165]])
tensor([[5.9163, 5.6644, 5.6165]])
tensor([[5.9163, 5.6644, 5.6165]])
tensor([[35.0028, 32.0849, 31.5454]])
tensor([[6.7727, 6.1339, 5.9020]])
tensor([[64.7350, 62.4088, 62.0225]])


### 行列の演算

In [7]:
v = torch.rand(1, 3)
x = torch.rand(5, 3)
y = torch.rand(5, 3)
result = torch.rand(5, 3)

# 行列とスカラー
print(x * 2.0)
# 行列とベクトル
print(x + v)
# 行列同士
print(x + y)
print(x * y)
print(x @ y.t())

tensor([[1.0052, 0.3446, 1.0514],
        [1.7925, 0.8667, 1.0488],
        [0.0190, 0.2442, 0.8130],
        [1.6858, 0.7823, 0.9329],
        [1.5835, 0.2748, 1.0573]])
tensor([[1.1914, 0.5841, 0.9183],
        [1.5851, 0.8452, 0.9170],
        [0.6983, 0.5339, 0.7991],
        [1.5317, 0.8030, 0.8590],
        [1.4805, 0.5492, 0.9213]])
tensor([[1.0204, 0.8031, 1.1890],
        [1.8774, 0.9112, 1.1768],
        [0.0110, 0.4524, 0.4300],
        [1.7430, 0.6463, 1.4525],
        [1.2001, 1.0730, 1.3931]])
tensor([[2.6026e-01, 1.0870e-01, 3.4869e-01],
        [8.7935e-01, 2.0710e-01, 3.4211e-01],
        [1.3921e-05, 4.0321e-02, 9.5585e-03],
        [7.5873e-01, 9.9801e-02, 4.5993e-01],
        [3.2328e-01, 1.2856e-01, 4.5700e-01]])
tensor([[0.7176, 0.9184, 0.0700, 1.0147, 0.8209],
        [1.0853, 1.4285, 0.1568, 1.4344, 1.2248],
        [0.3516, 0.3329, 0.0499, 0.4405, 0.4695],
        [0.9926, 1.3182, 0.1414, 1.3185, 1.1134],
        [0.8473, 1.1873, 0.0590, 1.2690, 0.9088]])


### 数学関数

In [8]:
X = torch.rand(3, 5)

# 平均値
m = torch.mean(X)
m = X.mean()
# 行ごとの平均値
print(X.mean(0))

tensor([0.6613, 0.5746, 0.3289, 0.4664, 0.5557])
