In [1]:
import torch
import numpy as np

# Tensorとは？
- 多次元配列を扱うためのデータ構造
- Numpyのndarrayとほぼ同様のAPIを有しており、GPUによる計算もサポートしている
- PyTorchにおいてテンソルはGPU上でも使用できるため、処理速度の向上させることも可能

## Tensorの初期化

In [2]:
# 初期化されていない行列の作成
print(torch.empty(3, 5))

# 乱数によって初期化された行列の作成
print(torch.rand(3, 5))

# 数値を指定した行列の作成
print(torch.tensor([5.5, 3]))

# 数値0で初期化された行列の作成
print(torch.zeros(3, 5))

# long型の数値1で初期化された行列の作成
print(torch.ones(3, 5, dtype = torch.long))

# データタイプの確認
print(f"Datatype of tensor : {torch.ones(3, 5, dtype = torch.long).dtype}")

# deviceを指定することで CPU or GPU 上にTensorを作成する
print(torch.rand(3, 5, device="cpu"))

# GPUが使用可能か確認する
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

# GPUが使用可能であれば、GPU上にtensorを移動させる
tensor = torch.rand(3, 5)
if torch.cuda.is_available():
    tensor = tensor.to(device)

# Tensorがどこに格納されているか確認
print(f"Device tensor is store on : {tensor.device}")

# 0～9までの値で初期化された1次元行列の作成
print(torch.arange(0, 10))

tensor([[-1.2040e+33,  3.0780e-41, -1.2084e+33,  3.0780e-41,  8.9683e-44],
        [ 0.0000e+00,  1.1210e-43,  0.0000e+00, -1.2068e+33,  3.0780e-41],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])
tensor([[0.7909, 0.5317, 0.0670, 0.7291, 0.3526],
        [0.3139, 0.6002, 0.1121, 0.3042, 0.8266],
        [0.4753, 0.2406, 0.1524, 0.7255, 0.5230]])
tensor([5.5000, 3.0000])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])
Datatype of tensor : torch.int64
tensor([[0.2942, 0.7175, 0.6373, 0.3523, 0.3605],
        [0.1571, 0.1841, 0.5757, 0.4382, 0.2440],
        [0.9235, 0.9021, 0.0079, 0.6347, 0.5139]])
Using cpu device
Device tensor is store on : cpu
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


## ndarrayとTensorの変換
注：変換前の行列の値を変更すると、変更後の行列も値が変化する

In [3]:
tensor = torch.rand(2, 3)
# Tensor -> Numpy ndarray
# 注：GPU上のtensorはCPU上に移動させる必要がある
np_array = np.array(tensor)
np_array = tensor.numpy()
print(f"numpy : \n{np_array}")

# Numpy ndarray -> Tensor
tensor = torch.from_numpy(np_array)
print(f"tensor : \n{tensor}")

numpy : 
[[0.8447152  0.10116208 0.6624328 ]
 [0.952541   0.80863863 0.96336144]]
tensor : 
tensor([[0.8447, 0.1012, 0.6624],
        [0.9525, 0.8086, 0.9634]])


## Tensorのインデンシング操作

In [4]:
tensor = torch.rand(4, 4)
# インデックスを指定
print(tensor[0, 1])

# 中の値だけの取り出し
print(f"row(%d) col(%d) is value : %f" % (0, 1, tensor[0, 1].item()))

# 行の取り出し
print("First row : ", tensor[0, :])

# 列の取り出し
print("First column : ", tensor[:, 0])
print("Last column  : ", tensor[:, -1])

# スライスでの取り出し
print(tensor[:, :2])
print(tensor[:, [1, 2]])

# マスク配列を使用して特定の値より大きい部分のみを選択
print(tensor[tensor > 0.5])

# インデックス・スライスを使用した一括代入
tensor[0, 1] = 100
tensor[:, -1] = 200
print(tensor)

# 特定条件の要素のみ置換
tensor[tensor > 0.5] = 1
print(tensor)

tensor(0.0782)
row(0) col(1) is value : 0.078191
First row :  tensor([0.2412, 0.0782, 0.1467, 0.2905])
First column :  tensor([0.2412, 0.9105, 0.4479, 0.5415])
Last column  :  tensor([0.2905, 0.6604, 0.8548, 0.6784])
tensor([[0.2412, 0.0782],
        [0.9105, 0.2919],
        [0.4479, 0.4475],
        [0.5415, 0.0578]])
tensor([[0.0782, 0.1467],
        [0.2919, 0.5164],
        [0.4475, 0.2894],
        [0.0578, 0.3232]])
tensor([0.9105, 0.5164, 0.6604, 0.8548, 0.5415, 0.6784])
tensor([[2.4124e-01, 1.0000e+02, 1.4675e-01, 2.0000e+02],
        [9.1052e-01, 2.9192e-01, 5.1639e-01, 2.0000e+02],
        [4.4790e-01, 4.4751e-01, 2.8941e-01, 2.0000e+02],
        [5.4153e-01, 5.7850e-02, 3.2322e-01, 2.0000e+02]])
tensor([[0.2412, 1.0000, 0.1467, 1.0000],
        [1.0000, 0.2919, 1.0000, 1.0000],
        [0.4479, 0.4475, 0.2894, 1.0000],
        [1.0000, 0.0578, 0.3232, 1.0000]])


## Tensorのサイズ操作

In [5]:
tensor = torch.rand(2, 8)
# Tensorサイズ≒Tensorの形
print(tensor.size())
# リサイズ
print(tensor)
tensor1 = tensor.view(1, 16)
print(tensor1)
tensor2 = tensor.view(-1, 4) # -1を指定するとほかに指定した次元の値から自動で計算
print(tensor2)

# 転置
print(tensor.t())

# 結合
print(torch.cat([tensor, tensor], dim = 0))

torch.Size([2, 8])
tensor([[0.8996, 0.1509, 0.5155, 0.2583, 0.7522, 0.3023, 0.4052, 0.0794],
        [0.2273, 0.4430, 0.2977, 0.6888, 0.0503, 0.5345, 0.7004, 0.7433]])
tensor([[0.8996, 0.1509, 0.5155, 0.2583, 0.7522, 0.3023, 0.4052, 0.0794, 0.2273,
         0.4430, 0.2977, 0.6888, 0.0503, 0.5345, 0.7004, 0.7433]])
tensor([[0.8996, 0.1509, 0.5155, 0.2583],
        [0.7522, 0.3023, 0.4052, 0.0794],
        [0.2273, 0.4430, 0.2977, 0.6888],
        [0.0503, 0.5345, 0.7004, 0.7433]])
tensor([[0.8996, 0.2273],
        [0.1509, 0.4430],
        [0.5155, 0.2977],
        [0.2583, 0.6888],
        [0.7522, 0.0503],
        [0.3023, 0.5345],
        [0.4052, 0.7004],
        [0.0794, 0.7433]])
tensor([[0.8996, 0.1509, 0.5155, 0.2583, 0.7522, 0.3023, 0.4052, 0.0794],
        [0.2273, 0.4430, 0.2977, 0.6888, 0.0503, 0.5345, 0.7004, 0.7433],
        [0.8996, 0.1509, 0.5155, 0.2583, 0.7522, 0.3023, 0.4052, 0.0794],
        [0.2273, 0.4430, 0.2977, 0.6888, 0.0503, 0.5345, 0.7004, 0.7433]])


## Tensorの演算
|演算子|説明|
|:-----|:---|
|dot|ベクトルの内積|
|mv|行列とベクトルの積|
|mm|行列と行列の積|
|matmul|引数の種類によって自動的にdot, mv, mmを選択して実行|
|gesv|LU分解による連立方程式の解|
|eig, symeig|固有値分解（symeigは対称行列用のより効率の良いアルゴリズム）|
|svd|特異値分解|

### ベクトルの演算

In [6]:
v1 = torch.rand([1, 3])
v2 = torch.rand([1, 3])
result = torch.zeros([1, 3])

# ベクトルとスカラーの足し算
print(v1 + 5)
print(torch.add(v1, 5))
print(torch.add(v1, 5, out = result)) # 出力先を引数で指定
print(v1.add_(5)) # Tensorそのものの変更（ip-place：インプレース処理）

# ベクトルの累乗
print(v1 ** 2)

# ベクトル同士の演算
print(v1 + v2)

# 複数の組み合わせ
print(v1 * 10 - v2 / 2 + 6)

tensor([[5.2536, 5.3174, 5.1213]])
tensor([[5.2536, 5.3174, 5.1213]])
tensor([[5.2536, 5.3174, 5.1213]])
tensor([[5.2536, 5.3174, 5.1213]])
tensor([[27.6008, 28.2751, 26.2280]])
tensor([[5.8120, 5.5836, 5.7309]])
tensor([[58.2573, 59.0413, 56.9085]])


### 行列の演算

In [7]:
v = torch.rand(1, 3)
x = torch.rand(5, 3)
y = torch.rand(5, 3)
result = torch.rand(5, 3)

# 行列とスカラー
print(x * 2.0)
# 行列とベクトル
print(x + v)
# 行列同士
print(x + y)
print(x * y)
print(x @ y.t())

tensor([[1.3044, 1.8155, 0.2715],
        [1.1546, 1.9507, 0.8573],
        [0.3382, 0.3250, 1.6431],
        [1.7122, 0.0648, 0.1763],
        [1.4542, 1.4307, 1.1143]])
tensor([[1.4873, 1.2642, 0.9681],
        [1.4124, 1.3318, 1.2610],
        [1.0042, 0.5190, 1.6539],
        [1.6912, 0.3889, 0.9205],
        [1.5622, 1.0718, 1.3895]])
tensor([[0.6931, 1.4612, 0.2765],
        [0.7199, 1.0377, 1.4115],
        [0.3338, 0.3789, 0.9957],
        [0.9465, 0.0655, 0.5174],
        [0.7981, 1.3941, 1.4096]])
tensor([[0.0267, 0.5024, 0.0191],
        [0.0823, 0.0609, 0.4213],
        [0.0278, 0.0352, 0.1431],
        [0.0774, 0.0011, 0.0378],
        [0.0516, 0.4856, 0.4750]])
tensor([[0.5481, 0.2831, 0.3275, 0.1473, 0.7782],
        [0.6237, 0.5645, 0.3808, 0.2685, 1.0685],
        [0.2125, 0.8417, 0.2061, 0.3733, 0.8227],
        [0.0653, 0.2108, 0.1633, 0.1163, 0.1579],
        [0.5040, 0.6959, 0.3716, 0.3285, 1.0122]])


### 数学関数

In [8]:
X = torch.rand(3, 5)

# 平均値
m = torch.mean(X)
m = X.mean()
# 行ごとの平均値
print(X.mean(0))

tensor([0.8120, 0.3952, 0.3219, 0.3421, 0.6423])
