In [1]:
import torch
import numpy as np

/usr/local/lib/python3.10/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


# Tensorとは？
- 多次元配列を扱うためのデータ構造
- Numpyのndarrayとほぼ同様のAPIを有しており、GPUによる計算もサポートしている
- PyTorchにおいてテンソルはGPU上でも使用できるため、処理速度の向上させることも可能

## Tensorの初期化

In [2]:
# 初期化されていない行列の作成
print(torch.empty(3, 5))

# 乱数によって初期化された行列の作成
print(torch.rand(3, 5))

# 数値を指定した行列の作成
print(torch.tensor([5.5, 3]))

# 数値0で初期化された行列の作成
print(torch.zeros(3, 5))

# long型の数値1で初期化された行列の作成
print(torch.ones(3, 5, dtype = torch.long))

# データタイプの確認
print(f"Datatype of tensor : {torch.ones(3, 5, dtype = torch.long).dtype}")

# deviceを指定することで CPU or GPU 上にTensorを作成する
print(torch.rand(3, 5, device="cpu"))

# GPUが使用可能か確認する
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

# GPUが使用可能であれば、GPU上にtensorを移動させる
tensor = torch.rand(3, 5)
if torch.cuda.is_available():
    tensor = tensor.to(device)

# Tensorがどこに格納されているか確認
print(f"Device tensor is store on : {tensor.device}")

# 0～9までの値で初期化された1次元行列の作成
print(torch.arange(0, 10))

tensor([[-1.0718e+20,  4.5555e-41,  6.0033e+08,  3.0967e-41,  1.4013e-45],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  6.0193e+08,  3.0967e-41,  2.0952e+08]])
tensor([[0.0668, 0.3532, 0.5167, 0.8630, 0.4749],
        [0.3916, 0.3439, 0.5391, 0.2951, 0.7480],
        [0.2375, 0.0691, 0.3074, 0.7506, 0.8561]])
tensor([5.5000, 3.0000])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])
Datatype of tensor : torch.int64
tensor([[0.0168, 0.7704, 0.7298, 0.2490, 0.6084],
        [0.6667, 0.0754, 0.7737, 0.1239, 0.6310],
        [0.8604, 0.7511, 0.3920, 0.1591, 0.7148]])
Using cpu device
Device tensor is store on : cpu
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


## ndarrayとTensorの変換
注：変換前の行列の値を変更すると、変更後の行列も値が変化する

In [3]:
tensor = torch.rand(2, 3)
# Tensor -> Numpy ndarray
# 注：GPU上のtensorはCPU上に移動させる必要がある
np_array = np.array(tensor)
np_array = tensor.numpy()
print(f"numpy : \n{np_array}")

# Numpy ndarray -> Tensor
tensor = torch.from_numpy(np_array)
print(f"tensor : \n{tensor}")

numpy : 
[[0.44133776 0.8737482  0.4701659 ]
 [0.9902563  0.36201388 0.8337458 ]]
tensor : 
tensor([[0.4413, 0.8737, 0.4702],
        [0.9903, 0.3620, 0.8337]])


## Tensorのインデンシング操作

In [4]:
tensor = torch.rand(4, 4)
# インデックスを指定
print(tensor[0, 1])

# 中の値だけの取り出し
print(f"row(%d) col(%d) is value : %f" % (0, 1, tensor[0, 1].item()))

# 行の取り出し
print("First row : ", tensor[0, :])

# 列の取り出し
print("First column : ", tensor[:, 0])
print("Last column  : ", tensor[:, -1])

# スライスでの取り出し
print(tensor[:, :2])
print(tensor[:, [1, 2]])

# マスク配列を使用して特定の値より大きい部分のみを選択
print(tensor[tensor > 0.5])

# インデックス・スライスを使用した一括代入
tensor[0, 1] = 100
tensor[:, -1] = 200
print(tensor)

# 特定条件の要素のみ置換
tensor[tensor > 0.5] = 1
print(tensor)

tensor(0.5724)
row(0) col(1) is value : 0.572383
First row :  tensor([0.2294, 0.5724, 0.7280, 0.1621])
First column :  tensor([0.2294, 0.5912, 0.5818, 0.7472])
Last column  :  tensor([0.1621, 0.7307, 0.7044, 0.2186])
tensor([[0.2294, 0.5724],
        [0.5912, 0.3524],
        [0.5818, 0.0786],
        [0.7472, 0.1493]])
tensor([[0.5724, 0.7280],
        [0.3524, 0.3198],
        [0.0786, 0.8107],
        [0.1493, 0.2715]])
tensor([0.5724, 0.7280, 0.5912, 0.7307, 0.5818, 0.8107, 0.7044, 0.7472])
tensor([[2.2943e-01, 1.0000e+02, 7.2800e-01, 2.0000e+02],
        [5.9116e-01, 3.5237e-01, 3.1978e-01, 2.0000e+02],
        [5.8181e-01, 7.8574e-02, 8.1073e-01, 2.0000e+02],
        [7.4720e-01, 1.4928e-01, 2.7153e-01, 2.0000e+02]])
tensor([[0.2294, 1.0000, 1.0000, 1.0000],
        [1.0000, 0.3524, 0.3198, 1.0000],
        [1.0000, 0.0786, 1.0000, 1.0000],
        [1.0000, 0.1493, 0.2715, 1.0000]])


## Tensorのサイズ操作

In [5]:
tensor = torch.rand(2, 8)
# Tensorサイズ≒Tensorの形
print(tensor.size())
# リサイズ
print(tensor)
tensor1 = tensor.view(1, 16)
print(tensor1)
tensor2 = tensor.view(-1, 4) # -1を指定するとほかに指定した次元の値から自動で計算
print(tensor2)

# 転置
print(tensor.t())

# 結合
print(torch.cat([tensor, tensor], dim = 0))

torch.Size([2, 8])
tensor([[0.3784, 0.1094, 0.3528, 0.3703, 0.2346, 0.9212, 0.3278, 0.0916],
        [0.3153, 0.0667, 0.0118, 0.7822, 0.9578, 0.4243, 0.7888, 0.8291]])
tensor([[0.3784, 0.1094, 0.3528, 0.3703, 0.2346, 0.9212, 0.3278, 0.0916, 0.3153,
         0.0667, 0.0118, 0.7822, 0.9578, 0.4243, 0.7888, 0.8291]])
tensor([[0.3784, 0.1094, 0.3528, 0.3703],
        [0.2346, 0.9212, 0.3278, 0.0916],
        [0.3153, 0.0667, 0.0118, 0.7822],
        [0.9578, 0.4243, 0.7888, 0.8291]])
tensor([[0.3784, 0.3153],
        [0.1094, 0.0667],
        [0.3528, 0.0118],
        [0.3703, 0.7822],
        [0.2346, 0.9578],
        [0.9212, 0.4243],
        [0.3278, 0.7888],
        [0.0916, 0.8291]])
tensor([[0.3784, 0.1094, 0.3528, 0.3703, 0.2346, 0.9212, 0.3278, 0.0916],
        [0.3153, 0.0667, 0.0118, 0.7822, 0.9578, 0.4243, 0.7888, 0.8291],
        [0.3784, 0.1094, 0.3528, 0.3703, 0.2346, 0.9212, 0.3278, 0.0916],
        [0.3153, 0.0667, 0.0118, 0.7822, 0.9578, 0.4243, 0.7888, 0.8291]])


## Tensorの演算
|演算子|説明|
|:-----|:---|
|dot|ベクトルの内積|
|mv|行列とベクトルの積|
|mm|行列と行列の積|
|matmul|引数の種類によって自動的にdot, mv, mmを選択して実行|
|gesv|LU分解による連立方程式の解|
|eig, symeig|固有値分解（symeigは対称行列用のより効率の良いアルゴリズム）|
|svd|特異値分解|

### ベクトルの演算

In [6]:
v1 = torch.rand([1, 3])
v2 = torch.rand([1, 3])
result = torch.zeros([1, 3])

# ベクトルとスカラーの足し算
print(v1 + 5)
print(torch.add(v1, 5))
print(torch.add(v1, 5, out = result)) # 出力先を引数で指定
print(v1.add_(5)) # Tensorそのものの変更（ip-place：インプレース処理）

# ベクトルの累乗
print(v1 ** 2)

# ベクトル同士の演算
print(v1 + v2)

# 複数の組み合わせ
print(v1 * 10 - v2 / 2 + 6)

tensor([[5.5253, 5.3234, 5.3110]])
tensor([[5.5253, 5.3234, 5.3110]])
tensor([[5.5253, 5.3234, 5.3110]])
tensor([[5.5253, 5.3234, 5.3110]])
tensor([[30.5285, 28.3385, 28.2063]])
tensor([[6.1814, 5.8849, 5.3206]])
tensor([[60.9245, 58.9531, 59.1048]])


### 行列の演算

In [7]:
v = torch.rand(1, 3)
x = torch.rand(5, 3)
y = torch.rand(5, 3)
result = torch.rand(5, 3)

# 行列とスカラー
print(x * 2.0)
# 行列とベクトル
print(x + v)
# 行列同士
print(x + y)
print(x * y)
print(x @ y.t())

tensor([[0.3098, 1.5720, 0.1964],
        [0.1727, 1.0217, 1.1465],
        [0.5348, 0.4168, 0.0320],
        [1.0469, 1.8089, 0.6708],
        [1.0705, 0.4948, 1.2040]])
tensor([[0.2196, 1.0209, 0.5182],
        [0.1511, 0.7457, 0.9932],
        [0.3321, 0.4433, 0.4360],
        [0.5882, 1.1393, 0.7554],
        [0.6000, 0.4823, 1.0220]])
tensor([[0.9533, 1.7293, 0.3352],
        [0.7810, 1.2795, 1.3210],
        [0.4132, 0.9810, 0.0762],
        [0.8034, 1.1286, 0.3799],
        [0.8606, 0.3149, 1.3593]])
tensor([[0.1237, 0.7414, 0.0233],
        [0.0600, 0.3927, 0.4286],
        [0.0390, 0.1610, 0.0010],
        [0.1465, 0.2027, 0.0149],
        [0.1741, 0.0167, 0.4559]])
tensor([[0.8884, 0.7852, 0.6358, 0.2239, 0.1778],
        [0.6866, 0.8813, 0.4418, 0.1642, 0.4967],
        [0.4138, 0.3579, 0.2010, 0.1223, 0.1132],
        [1.3505, 1.3096, 0.7953, 0.3642, 0.4853],
        [0.8034, 1.0121, 0.3054, 0.2321, 0.6467]])


### 数学関数

In [8]:
X = torch.rand(3, 5)

# 平均値
m = torch.mean(X)
m = X.mean()
# 行ごとの平均値
print(X.mean(0))

tensor([0.6238, 0.3358, 0.5755, 0.3134, 0.5836])
