In [2]:
import torch
import numpy as np

# Tensorとは？
- 多次元配列を扱うためのデータ構造
- Numpyのndarrayとほぼ同様のAPIを有しており、GPUによる計算もサポートしている
- PyTorchにおいてテンソルはGPU上でも使用できるため、処理速度の向上させることも可能

## Tensorの初期化

In [3]:
# 初期化されていない行列の作成
print(torch.empty(3, 5))

# 乱数によって初期化された行列の作成
print(torch.rand(3, 5))

# 数値を指定した行列の作成
print(torch.tensor([5.5, 3]))

# 数値0で初期化された行列の作成
print(torch.zeros(3, 5))

# long型の数値1で初期化された行列の作成
print(torch.ones(3, 5, dtype = torch.long))

# データタイプの確認
print(f"Datatype of tensor : {torch.ones(3, 5, dtype = torch.long).dtype}")

# deviceを指定することで CPU or GPU 上にTensorを作成する
print(torch.rand(3, 5, device="cpu"))

# GPUが使用可能か確認する
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

# GPUが使用可能であれば、GPU上にtensorを移動させる
tensor = torch.rand(3, 5)
if torch.cuda.is_available():
    tensor = tensor.to(device)

# Tensorがどこに格納されているか確認
print(f"Device tensor is store on : {tensor.device}")

# 0～9までの値で初期化された1次元行列の作成
print(torch.arange(0, 10))

tensor([[-5.1887e+01,  3.0642e-41, -5.2364e+01,  3.0642e-41,  8.9683e-44],
        [ 0.0000e+00,  1.1210e-43,  0.0000e+00, -5.2122e+01,  3.0642e-41],
        [ 2.8026e-45,  0.0000e+00,  2.8026e-45,  0.0000e+00,  4.2039e-45]])
tensor([[0.4859, 0.5184, 0.3040, 0.4576, 0.8065],
        [0.8655, 0.4487, 0.7136, 0.1736, 0.7559],
        [0.7717, 0.6424, 0.2221, 0.6960, 0.4995]])
tensor([5.5000, 3.0000])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]])
Datatype of tensor : torch.int64
tensor([[0.6474, 0.2102, 0.1128, 0.1296, 0.5212],
        [0.3053, 0.5340, 0.5268, 0.8027, 0.7459],
        [0.8784, 0.7537, 0.0932, 0.2859, 0.9485]])
Using cpu device
Device tensor is store on : cpu
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


## ndarrayとTensorの変換
注：変換前の行列の値を変更すると、変更後の行列も値が変化する

In [3]:
tensor = torch.rand(2, 3)
# Tensor -> Numpy ndarray
# 注：GPU上のtensorはCPU上に移動させる必要がある
np_array = np.array(tensor)
np_array = tensor.numpy()
print(f"numpy : \n{np_array}")

# Numpy ndarray -> Tensor
tensor = torch.from_numpy(np_array)
print(f"tensor : \n{tensor}")

numpy : 
[[0.19423854 0.71500087 0.07401246]
 [0.16072899 0.36175    0.5611271 ]]
tensor : 
tensor([[0.1942, 0.7150, 0.0740],
        [0.1607, 0.3618, 0.5611]])


## Tensorのインデンシング操作

In [4]:
tensor = torch.rand(4, 4)
# インデックスを指定
print(tensor[0, 1])

# 中の値だけの取り出し
print(f"row(%d) col(%d) is value : %f" % (0, 1, tensor[0, 1].item()))

# 行の取り出し
print("First row : ", tensor[0, :])

# 列の取り出し
print("First column : ", tensor[:, 0])
print("Last column  : ", tensor[:, -1])

# スライスでの取り出し
print(tensor[:, :2])
print(tensor[:, [1, 2]])

# マスク配列を使用して特定の値より大きい部分のみを選択
print(tensor[tensor > 0.5])

# インデックス・スライスを使用した一括代入
tensor[0, 1] = 100
tensor[:, -1] = 200
print(tensor)

# 特定条件の要素のみ置換
tensor[tensor > 0.5] = 1
print(tensor)

tensor(0.0476)
row(0) col(1) is value : 0.047623
First row :  tensor([0.1933, 0.0476, 0.5052, 0.0042])
First column :  tensor([0.1933, 0.4205, 0.3509, 0.8398])
Last column  :  tensor([0.0042, 0.0306, 0.5422, 0.7232])
tensor([[0.1933, 0.0476],
        [0.4205, 0.9301],
        [0.3509, 0.9534],
        [0.8398, 0.7210]])
tensor([[0.0476, 0.5052],
        [0.9301, 0.6571],
        [0.9534, 0.5824],
        [0.7210, 0.1559]])
tensor([0.5052, 0.9301, 0.6571, 0.9534, 0.5824, 0.5422, 0.8398, 0.7210, 0.7232])
tensor([[1.9328e-01, 1.0000e+02, 5.0520e-01, 2.0000e+02],
        [4.2051e-01, 9.3013e-01, 6.5712e-01, 2.0000e+02],
        [3.5090e-01, 9.5337e-01, 5.8236e-01, 2.0000e+02],
        [8.3984e-01, 7.2103e-01, 1.5589e-01, 2.0000e+02]])
tensor([[0.1933, 1.0000, 1.0000, 1.0000],
        [0.4205, 1.0000, 1.0000, 1.0000],
        [0.3509, 1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 0.1559, 1.0000]])


## Tensorのサイズ操作

In [5]:
tensor = torch.rand(2, 8)
# Tensorサイズ≒Tensorの形
print(tensor.size())
# リサイズ
print(tensor)
tensor1 = tensor.view(1, 16)
print(tensor1)
tensor2 = tensor.view(-1, 4) # -1を指定するとほかに指定した次元の値から自動で計算
print(tensor2)

# 転置
print(tensor.t())

# 結合
print(torch.cat([tensor, tensor], dim = 0))

torch.Size([2, 8])
tensor([[0.4375, 0.4516, 0.2099, 0.3314, 0.4738, 0.3070, 0.1880, 0.8082],
        [0.1690, 0.1615, 0.2863, 0.6514, 0.3008, 0.8939, 0.0750, 0.3007]])
tensor([[0.4375, 0.4516, 0.2099, 0.3314, 0.4738, 0.3070, 0.1880, 0.8082, 0.1690,
         0.1615, 0.2863, 0.6514, 0.3008, 0.8939, 0.0750, 0.3007]])
tensor([[0.4375, 0.4516, 0.2099, 0.3314],
        [0.4738, 0.3070, 0.1880, 0.8082],
        [0.1690, 0.1615, 0.2863, 0.6514],
        [0.3008, 0.8939, 0.0750, 0.3007]])
tensor([[0.4375, 0.1690],
        [0.4516, 0.1615],
        [0.2099, 0.2863],
        [0.3314, 0.6514],
        [0.4738, 0.3008],
        [0.3070, 0.8939],
        [0.1880, 0.0750],
        [0.8082, 0.3007]])
tensor([[0.4375, 0.4516, 0.2099, 0.3314, 0.4738, 0.3070, 0.1880, 0.8082],
        [0.1690, 0.1615, 0.2863, 0.6514, 0.3008, 0.8939, 0.0750, 0.3007],
        [0.4375, 0.4516, 0.2099, 0.3314, 0.4738, 0.3070, 0.1880, 0.8082],
        [0.1690, 0.1615, 0.2863, 0.6514, 0.3008, 0.8939, 0.0750, 0.3007]])


## Tensorの演算
|演算子|説明|
|:-----|:---|
|dot|ベクトルの内積|
|mv|行列とベクトルの積|
|mm|行列と行列の積|
|matmul|引数の種類によって自動的にdot, mv, mmを選択して実行|
|gesv|LU分解による連立方程式の解|
|eig, symeig|固有値分解（symeigは対称行列用のより効率の良いアルゴリズム）|
|svd|特異値分解|

### ベクトルの演算

In [6]:
v1 = torch.rand([1, 3])
v2 = torch.rand([1, 3])
result = torch.zeros([1, 3])

# ベクトルとスカラーの足し算
print(v1 + 5)
print(torch.add(v1, 5))
print(torch.add(v1, 5, out = result)) # 出力先を引数で指定
print(v1.add_(5)) # Tensorそのものの変更（ip-place：インプレース処理）

# ベクトルの累乗
print(v1 ** 2)

# ベクトル同士の演算
print(v1 + v2)

# 複数の組み合わせ
print(v1 * 10 - v2 / 2 + 6)

tensor([[5.1855, 5.7337, 5.6179]])
tensor([[5.1855, 5.7337, 5.6179]])
tensor([[5.1855, 5.7337, 5.6179]])
tensor([[5.1855, 5.7337, 5.6179]])
tensor([[26.8892, 32.8749, 31.5604]])
tensor([[5.1900, 5.9354, 6.5618]])
tensor([[57.8526, 63.2358, 61.7067]])


### 行列の演算

In [7]:
v = torch.rand(1, 3)
x = torch.rand(5, 3)
y = torch.rand(5, 3)
result = torch.rand(5, 3)

# 行列とスカラー
print(x * 2.0)
# 行列とベクトル
print(x + v)
# 行列同士
print(x + y)
print(x * y)
print(x @ y.t())

tensor([[1.0090, 0.1086, 1.7785],
        [1.4376, 0.3305, 0.8539],
        [0.5017, 1.0804, 1.8823],
        [1.6531, 1.2929, 1.4507],
        [0.0750, 0.5568, 0.9971]])
tensor([[1.1462, 0.8558, 1.2800],
        [1.3605, 0.9668, 0.8177],
        [0.8925, 1.3417, 1.3319],
        [1.4683, 1.4480, 1.1161],
        [0.6792, 1.0799, 0.8893]])
tensor([[0.5985, 0.4089, 0.9535],
        [1.1478, 0.1737, 0.6832],
        [0.3875, 1.2317, 1.7187],
        [1.4826, 0.7051, 1.0883],
        [0.7905, 1.1329, 0.9343]])
tensor([[0.0474, 0.0193, 0.0571],
        [0.3084, 0.0014, 0.1094],
        [0.0343, 0.3736, 0.7318],
        [0.5423, 0.0379, 0.2633],
        [0.0282, 0.2379, 0.2172]])
tensor([[0.1238, 0.4447, 0.7979, 0.6569, 0.8138],
        [0.1536, 0.4191, 0.5445, 0.6362, 0.8685],
        [0.2756, 0.3533, 1.1396, 0.5379, 1.0606],
        [0.3535, 0.5459, 1.1240, 0.8435, 1.4909],
        [0.1343, 0.1462, 0.5853, 0.2219, 0.4834]])


### 数学関数

In [8]:
X = torch.rand(3, 5)

# 平均値
m = torch.mean(X)
m = X.mean()
# 行ごとの平均値
print(X.mean(0))

tensor([0.5499, 0.3828, 0.4359, 0.3448, 0.2579])
